name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # enables manual builds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Unit Test
        run: npm run test:unit

      - name: Integration Test
        run: npm run test:integration

      - name: Package
        run: npm run package

      - name: Deploy
        run: npm run deploy-only
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: System Test
        run: |
          BEARER_TOKEN=`AWS_PAGER="" aws cognito-idp initiate-auth --auth-flow USER_PASSWORD_AUTH --client-id 5dn5jkqc0h60h45g8hrf83mln --auth-parameters USERNAME=cicd-test-account,PASSWORD=${{ secrets.TEST_ACCOUNT_PASSWORD }} --region us-east-1 --query 'AuthenticationResult.AccessToken' --output text`
          curl https://banking-api.aws.georgemccarron.com/customers -H "Authorization: $BEARER_TOKEN"
          npm run test:system
