name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # enables manual builds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm run test:unit

      - name: Integration Test
        run: npm run test:integration

      - name: Package
        run: npm run package

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: npm run deploy-only
      
      - name: System Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cognito-idp admin-create-user \
            --user-pool-id us-east-1_T6MA1RsCR \
            --username test-user-${{ github.run_number }}-${{ github.run_attempt }} \
            --message-action SUPPRESS \
            --region us-east-1
          aws cognito-idp admin-set-user-password \
            --user-pool-id us-east-1_T6MA1RsCR \
            --username test-user-${{ github.run_number }}-${{ github.run_attempt }} \
            --password ${{ secrets.TEST_ACCOUNT_PASSWORD }} \
            --permanent \
            --region us-east-1
          export BEARER_TOKEN=`aws cognito-idp initiate-auth \
            --auth-flow USER_PASSWORD_AUTH \
            --client-id 5dn5jkqc0h60h45g8hrf83mln \
            --auth-parameters USERNAME=test-user-${{ github.run_number }}-${{ github.run_attempt }},PASSWORD=${{ secrets.TEST_ACCOUNT_PASSWORD }} \
            --region us-east-1 \
            --query 'AuthenticationResult.AccessToken' \
            --output text`
          npm run test:system
